name: Backend CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch


jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      matrix:
        node-version: [22] # Test on multiple Node.js versions


    environment: MONGO_URI

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Env Secret

      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: | 
        echo "Secret 1 is: $MONGO_URI"
        echo "Secret 2 is: $JWT_SECRET"
        echo "Secret 3 is: $PORT"
      
    - name: Stop Existing PM2 Processes
      shell: bash
      run: |
        if pm2 jlist | grep -q '"pm_id"'; then
          pm2 stop all
        else
          echo "No PM2 processes to stop"
        fi

    # Install dependencies for backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: | 
       npm install --global yarn
       yarn --version
       yarn install
      
    # Install dependencies for frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        df -h
        sudo rm -rf ./build
        yarn install
        yarn run build


    # Run backend tests
    - name: Run Backend Tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      working-directory: ./backend
      run: npm test

    - name: Seed Database
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      working-directory: ./backend
      run: npm run seed

    - run: npm ci
    - run: | 
        cd ./backend
        touch .env
        echo "${{ secrets.PROD }}" > .env

    - name: Start Backend with PM2
      run: pm2 startOrRestart ecosystem.config.js --update-env

    - name: Start or Reload Frontend with PM2
      shell: bash
      run: |
        if pm2 jlist | grep -q '"name":"Frontend"'; then
          pm2 restart Frontend
        else
          pm2 serve frontend/build 3000 --name Frontend --spa
        fi

    - name: Save PM2 Process List
      run: pm2 save